# The URL the site will be built for
base_url = "https://github.com/BConquest/hephaestus"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
about = "Undergraduate at The University of Alabama"

menu = [
{ text = "Home", link = "/" },
{ text = "About", link = "/about/" },
{ text = "Education", link = "/#education" },
{ text = "Skills", link = "/skills/" },
{ text = "Projects", link = "/projects/"}
]


social = [
{ user = "paxavis", link = "https://news.ycombinator.com/user?id=paxavis", icon = "logo-hackernews"},
{ user = "bryantnotdenny", link = "instagram.com", icon = "logo-instagram"},
{ user = "bryant@paxavis.dev", link = "mailto:bryant@paxavis.dev", icon = "mail-outline"},
{ user = "@paxavis@mastodon.social", link = "https://mastodon.social/@paxavis", icon ="logo-mastodon"}
]
