name = "hephaestus"
description = "A portfolio theme"
license = "AGPL"
homepage = "https://github.com/BConquest/hephaestus"
min_version = "0.4.0"
demo = "https://bryantconquest.com"

[extra]
about = "Undergraduate at The University of Alabama"
menu = [
{ text = "Home", link = "/" },
{ text = "About", link = "/about/" },
{ text = "Education", link = "/#education" },
{ text = "Skills", link = "/skills/" },
{ text = "Projects", link = "/projects/"}
]
social = [
]

[author]
name = "Bryant Conquest"
homepage = "https://bryantconquest.com"
